name: Feature Request
description: Suggest an idea or enhancement for go-flow
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea for go-flow!
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement / Use Case
      description: Is your feature request related to a specific problem or workflow?
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution / API Design
      description: Describe the solution or API you'd like to see.
      render: go
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered.
