name: Lint Actions

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - name: Run actionlint
        run: |
          GOPATH=$(go env GOPATH)
          "$GOPATH/bin/actionlint"
