name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Index on pkg.go.dev
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          VERSION="${{ steps.release.outputs.tag_name }}"
          GOPROXY=https://proxy.golang.org GO111MODULE=on go list -m github.com/ntkwan/go-flow@${VERSION} || true
